---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: jenkins-data
        namespace: dwikikurnia
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 2Gi
        storageClassName: gold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jenkins
    service: master
  name: jenkins-master
  namespace: dwikikurnia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      service: master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
        service: master
    spec:
      containers:
      - image: jenkins/jenkins:lts-alpine
        name: jenkins
        resources:
                limits:
                        cpu: 2
                        memory: 1Gi
                requests:
                        cpu: 200m
                        memory: 500Mi

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
        annotations:
                kubernetes.io/ingress.class: nginx
        name: jenkins-master
        namespace: dwikikurnia
spec:
        rules:
        - host: jenkins.dwikikurnia.me
          http:
                paths:
                - backend:
                        serviceName: jenkins-master
                        servicePort: 8080
